### ISSUE TITLE
Add threshold feature that enables non-zero exit code if metric is below set value

### ISSUE THREAD

**Issue by aaronfowles** [tonybaloney/wily#104]
It would be useful to specify a threshold for metrics so that CI could detect if a metric has fallen below a certain threshold. Eg:
```
wily build src/
wily rank --threshold=80
```
if the `Total` value is less than the threshold, a non-zero exit code will get chucked out that the CI can pick up.

**Comment by aaronfowles** [comment]
Ah, it seems this is probably a sub-set of #66 .

**Comment by tonybaloney** [comment]
Hi @aaronfowles I agree this would be a useful feature. there's a WIP PR in the backlog, I'll chase the author and we'll see if we can get it merged
