### ISSUE TITLE
Wily report fails: all metrics "not found"

### ISSUE THREAD

**Issue by skatromb** [tonybaloney/wily#108]
I've installed wily, run comman `wily build` and run command `wily report LinesCommenter3.0.py` but it shows zero report:
![image](https://user-images.githubusercontent.com/1759463/72867495-2cd20380-3cf0-11ea-82d1-2ff5e61cb89d.png)

Here's the source code for the Python program (I've renamed it to ".txt" because of GitHub upload file extension restriction)
[LinesCommenter3.0.txt](https://github.com/tonybaloney/wily/files/4095361/LinesCommenter3.0.txt)

At the same time wily doesn't fail at the file LinesCommenter.py with command `wily report LinesCommenter.py` (but the stats are not looking thruthful):
![image](https://user-images.githubusercontent.com/1759463/72867718-ea5cf680-3cf0-11ea-8b84-3de0b1254e9f.png)

Here's the source code:
[LinesCommenter.txt](https://github.com/tonybaloney/wily/files/4095375/LinesCommenter.txt)

Maybe I do something wrong?

**Comment by DahlitzFlorian** [comment]
I downloaded the files you provided, ran `wily build` in the directory both are located, followed by `wily report <file_name>.py`. Invoking `wily report` for each file printed a valid result.

I'm using the latest wily version at the time:

```shell
$ wily --version
🦊 wily, version 1.16.0
```

**Comment by skatromb** [comment]
Thank you for answer.
For now I've tried this again and have truthful report. I'll close the ticket therefore
