### ISSUE TITLE
Support for the $BROWSER env var being a full command, not just an executable

### ISSUE THREAD

**Issue by mandx** [tonybaloney/wily#11]
When showing graphs, Wily crashes in my local setup because my `$BROWSER` environment variable is actually a command (`program-name --option1 --option2` etc) and not an executable available in $PATH. Setting `$BROWSER` to just the binary name did make the graph show up.

**Comment by tonybaloney** [comment]
What is the value of the $browser variable in your environment? Might be a bug in plotly 

What happens if you do 
```python
import webbrowser
webbrowser.open(‘https://google.com’)
```

**Comment by tonybaloney** [comment]
@mandx I just released 1.3.0.dev0, a beta release. The graph command now has an `-o` or `--output` option. If you put a filename there it won't try and open the browser it will just generate the file.

e.g.

```console
wily graph path/to/file.py <metric> --output report.html
```

**Comment by mandx** [comment]
@tonybaloney Hey, sorry for the late reply.

Yes, the problem lies in the `webbrowser` module, I can easily reproduce the issue with you code snippet, also confirming that the original problem can't be cleanly fixed from Wily, so now I personally consider the issue "fixed" (or at the very least, addressed) with the introduction of the `--output` argument.

I'll leave it to you to decide to close this ticket or not.

**Comment by tonybaloney** [comment]
"**When the value of a list part contains the string %s, then it is interpreted as a literal browser command line to be used with the argument URL substituted for %s; if the part does not contain %s, it is simply interpreted as the name of the browser to launch**"

So, make sure the %s character is in the $BROWSER envvar, I tested that quickly: 

```
➜  ~ BROWSER="echo -n" python3 browse.py
➜  ~ BROWSER="echo -n %s" python3 browse.py
https://google.com%        
```
