### ISSUE TITLE
A couple of problems, is doc too old?

### ISSUE THREAD

**Issue by eric-saintetienne** [tonybaloney/wily#113]
Installed `wily==1.16.0` and there are two main problems with running wily:

The pypi page at https://pypi.org/project/wily says to use this line in `wili.cfg`:
```
operators = cyclomatic,raw
```
But then `wily` excepts without a proper error message (it chokes on the first character `c`)

Then the same site says to use `wily graph` but that doesn't work:
```
$ wily graph
Usage: wily graph [OPTIONS] PATH METRICS...
Try 'wily graph --help' for help.

Error: Missing argument 'PATH'.
```

The pypi site needs updating, thank you.

**Comment by tonybaloney** [comment]
@eric-saintetienne the operators argument is being fixed in #116 thanks for reporting

The second issue you reported is because you did not provide a PATH argument (path to the file(s) to graph)
