### ISSUE TITLE
add possibility to load `cache_path` option from `wily.cfg`

### ISSUE THREAD

**Issue by skarzi** [tonybaloney/wily#117]
Hello,

first of all, thanks for developing `wily`!

**Is your feature request related to a problem? Please describe.**

Adding `cache_path` option to `wily.cfg` will make using custom cache path much, much easier, because developers won't be force to add `--cache` CLI option in every command call.

**Describe the solution you'd like**

Add `cache_path` to `wily.cfg`.

**Comment by tonybaloney** [comment]
Great idea, is that not already a possibility?

**Comment by skarzi** [comment]
Currently it's not possible, the only options that can be read from `wily.cfg` are:

+ `operators`
+ `archiver`
+ `path`
+ `max_revisions`
+ `include_ipynb`
+ `ipynb_cells`

**Comment by tonybaloney** [comment]
Ah ok, I understand. I'd support this feature, if you'd like to develop this and raise a PR?

**Comment by skarzi** [comment]
Sure, I would like to prepare PR :+1:
