### ISSUE TITLE
wily --help throws TypeError

### ISSUE THREAD

**Issue by 0LL13** [tonybaloney/wily#119]
Thank you for wily, it worked for me in a different project, however suddenly it throws this error. Sorry if this is not a bug but sth else!

**Describe the bug**
wily was installed with pipenv and is listed when using pip list
command $ wily --help throws 
.../.local/share/virtualenvs/person-iI0pDqHU/lib/python3.8/site-packages/wily/__init__.py", line 18, in <module>
    _filehandler = logging.FileHandler(WILY_LOG_NAME, mode="w+")
  File "/usr/lib/python3.8/logging/__init__.py", line 1130, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not tuple

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] linux/ubuntu 20.04

**Comment by DahlitzFlorian** [comment]
I can confirm this behaviour on Ubuntu 20.04 and Pipenv for Python 3.7, 3.8, and 3.9.

**Comment by skarzi** [comment]
This issue was related to how [`flit`](https://github.com/takluyver/flit) handles the package's `version` detection, but it was fixed in https://github.com/tonybaloney/wily/commit/20b1b37a4032c01ed711e93e074085d3551aa582.
Please bump `wily` to the latest version (`1.18.0`) to resolve this issue.

**Comment by 0LL13** [comment]
Yes, works again. Thank you!
