### ISSUE TITLE
Wily console output shows values in green when they get worse and red when they get better.

### ISSUE THREAD

**Issue by ali1234** [tonybaloney/wily#127]
**Describe the bug**
When maintainability index drops, the change is shown in green. When it increases the change is shown in red. On the other hand, for cyclomatic complexity, this is reversed. It is my understanding that higher maintainability index is good, while higher complexity is bad. Therefore Wily is using green to indicate something bad, and red to indicate something good. This seems wrong.

**To Reproduce**
1. Just look at some wily reports on the console.

**Expected behavior**
Red should indicate something bad. Green should indicate something good.

**Screenshots**
![wily4](https://user-images.githubusercontent.com/651970/104325954-13b5fa00-54e1-11eb-9a71-b46f7c31a145.png)

Running Pycharm's terminal, Ubuntu 20.04, Python version 3.8.5, wily version 1.19.0

**Comment by tonybaloney** [comment]
released in 1.20.0
