### ISSUE TITLE
Build a ranking command

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/wily#13]
Build a command which can list files, methods or functions in order of any of the metrics, e.g. complexity.

Useful for reducing complexity.

**Comment by tonybaloney** [comment]
Command would behave like this:

```command
 $ wily rank [<path>] [<metric>] [--revision <revision>]
```
Would list all files in path and sort them in order of `<metric>`. If metric is "AimHigh", then sort by lowest first, and if "AimLow" then highest first.

`path` would default to __all__ files in the index across all archivers.

`metric` would default to `maintainability.index` (probably the best metric)

`revision` would default to the last __revision__, although maybe an extra flag for the actual files incase the repo is dirty. Revision should support full and short sha's.

**Comment by jwattier** [comment]
Hi @tonybaloney, I am interested in trying to implement this command. Will start nibbling at in next few days/over weekend and let you know any questions that I have - I am sure there will be some sense this is my first time diving into the code

**Comment by DahlitzFlorian** [comment]
Hey @jwattier! Are you still working on this and if so, do you make progress or do you need any help?

**Comment by jwattier** [comment]
Hi @DahlitzFlorian - Appreciate touching base and sorry for the delay. I had some minor surgery middle of last week + I have a little trouble waking up early enough (before kids get up) or working on this at night (after kids are in bed). I have made some updates on my local copy of the branch - but they are not significant. I am about to come up on a really busy several weeks at work starting next week. So I think come Sunday night/Monday morning I can WIP commit again whatever updates I have and then see if yourself or another person is able to take the baton.

**Comment by DahlitzFlorian** [comment]
Just let me know if it's up for grabs. Looking forward to your changes!

**Comment by jwattier** [comment]
Definitely. Will do. Thanks again for checking in. Feel bad for not keeping up more real time.

**Comment by jwattier** [comment]
Hey Guys - Apologies for lack of updates for a past 10 days. Someone on my team at work is leaving and that's throwing a bit of monkey wrench into my month. @DahlitzFlorian I haven't started on the test of the click CLI setup - if you would want to take and run with those two items.

**Comment by DahlitzFlorian** [comment]
Will have a look at it. Are all your changes pushed to the corresponding branch?

**Comment by jwattier** [comment]
They are. Thanks, appreciate it.
