### ISSUE TITLE
Red and green colours flipped in usage

### ISSUE THREAD

**Issue by dob9601** [tonybaloney/wily#130]
**Is your feature request related to a problem? Please describe.**
The colours indicating a change in code quality are ambiguous.
An increase in the maintainability index or a decrease in cyclomatic complexity is coloured red. giving it a negative connotation when these are positive things to occur. Likewise, vice versa

**Describe the solution you'd like**
The colours red and green to be flipped in their usage

**Describe alternatives you've considered**
N/A

**Additional context**
Runnning: `🦊 wily, version 1.19.0`

**Comment by dob9601** [comment]
After looking at your demo, this appears to be an issue with my specific instance of wily as opposed to the whole repo

**Comment by tonybaloney** [comment]
released in 1.20.0
