### ISSUE TITLE
Cant install wily due to dependency conflict with Click <8.0

### ISSUE THREAD

**Issue by commentator8** [tonybaloney/wily#142]
**Describe the bug**
I am trying to use wily but it fails to install due to it requiring Click < 8 and my project uses click 8.0. Is this arbitrary or can it be upgraded to use Click 8.0 also?

**To Reproduce**
require Click 8.0.* and try and install wily

**Expected behavior**
Wily should successfully install.

**Desktop (please complete the following information):**
 - OS: Mac

**Additional context**
```
❯ poetry add --dev wily
Using version ^1.20.0 for wily

Updating dependencies
Resolving dependencies... (3.0s)

  SolverProblemError

  Because no versions of wily match >1.20.0,<2.0.0
   and wily (1.20.0) depends on click (>=7.0,<8.0), wily (>=1.20.0,<2.0.0) requires click (>=7.0,<8.0).
  So, because analyzer-service depends on both click (8.0.*) and wily (^1.20.0), version solving failed.

  at ~/Library/Application Support/pypoetry/venv/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

**Comment by skarzi** [comment]
hi :wave: 

For some reason version, 1.21.0 of `wily` still depends on `click>=7.0,<8.0`.

Below you can find all dependencies of `wily==1.21.0` according to poetry:

```
[[package]]
name = "wily"
version = "1.21.0"
description = "A Python application for tracking, reporting on timing and complexity in tests and applications."
category = "dev"
optional = false
python-versions = ">=3.6"

[package.dependencies]
click = ">=7.0,<8.0"
colorlog = ">=4.0.0,<5.0.0"
gitpython = ">=3.0.0,<4.0.0"
nbformat = ">=5.1.3,<6.0.0"
plotly = ">=4.0.0,<5.0.0"
progress = "1.4"
radon = ">=4.0.0,<4.1.0"
tabulate = ">=0.8.2,<1.0.0"
```

**Comment by tonybaloney** [comment]
@skarzi What steps did you do to reproduce this? I'm looking at the sdist on PyPI and it has the correct dependencies

**Comment by skarzi** [comment]
The minimal example is to simply run `poetry add wily` or `pip install wily` inside a fresh virtual environment and in both cases, it installs `click==7.1.2`, because of the `click<8.0,>=7.0` constraint.
I have also inspected `wily-1.21.0.dist-info/METADATA` and it contains following line:

> Requires-Dist: click>=7.0,<8.0

So it seems like an unproperly built version of the `wily` package was uploaded to PyPI.

**Comment by astrojuanlu** [comment]
Should this issue be reopened then?
