### ISSUE TITLE
Package Wily on conda-forge?

### ISSUE THREAD

**Issue by Zeitsperre** [tonybaloney/wily#146]
I'm only starting to play around with wily, and I am wondering if there is any interest in offering a [conda-forge](https://conda-forge.org/) package of `wily`. I would be willing to help in contributing to the build recipe, if that helps!

**Comment by tonybaloney** [comment]
This would be great. I tried a few years ago and couldn't get anywhere https://github.com/conda-forge/staged-recipes/pull/10416

**Comment by Zeitsperre** [comment]
I only needed to make very minor modifications of your recipe. Package will be published when https://github.com/conda-forge/staged-recipes/pull/18520#issuecomment-1083365233 is merged.

All the best!

**Comment by tonybaloney** [comment]
Thanks for doing this!
