### ISSUE TITLE
Click version not matching in pyproject.toml

### ISSUE THREAD

**Issue by fleskovar** [tonybaloney/wily#160]
**Describe the bug**
Click version for [build-system] is "click>=7.0,<9.0" while for [tool.flit.metadata] it is "click>=7.0,<8.0". This probably caused the package uploaded to pypi to have the wrong requirements "click>=7.0,<8.0".

**To Reproduce**
1. pip install wily black
2. Fails saying that wily requires  "click>=7.0,<8.0"

**Expected behavior**
Expected versions for click should be "click>=7.0,<9.0"

**Comment by tonybaloney** [comment]
Looks like wily has come compatibility issue with click >8 so it's not quite as simple as updating the metadata. I'll work through the issues

**Comment by tonybaloney** [comment]
Fixed in 1.23.0
