### ISSUE TITLE
list-metrics outputs metrics in unpredictable order

### ISSUE THREAD

**Issue by devdanzin** [tonybaloney/wily#179]
The command list-metrics outputs metrics in unpredictable order, which might be confusing for users that expect it to be stable. (e.g. missing some info when skimming the output).

My actual issue was that I'm using `ALL_OPERATORS` to build an index of HTML reports, and there too the ordering is inconsistent. It seems it comes from using a set to build this dictionary:

```python
"""Dictionary of all operators"""
ALL_OPERATORS = {
    operator.name: operator
    for operator in {
        OPERATOR_CYCLOMATIC,
        OPERATOR_MAINTAINABILITY,
        OPERATOR_RAW,
        OPERATOR_HALSTEAD,
    }
}
```

This seems to be the root cause of #126. So I'd like to request the feature of stable ordering, likely by changing the set literal to a tuple literal. 

I've solved my issue by sorting `ALL_OPERATORS.items()`, then saw that it also affects list-metrics.

I can submit a PR if it's considered a desirable change.

**Comment by tonybaloney** [comment]
Hm, yes I never considered the set literal would yield different orders. 

Please submit a PR and swap that set literal with a tuple literal
