### ISSUE TITLE
Add ability to report on or graph a directory

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/wily#19]
Add ability to specify a path in `wily graph`, which will recursively add all the Python files in the current path. 

e.g. `wily graph src/ raw.loc`, `wily graph src/tests/ cyclomatic.complexity raw.loc`

Must work with `--path` as well

**Comment by tonybaloney** [comment]
#20

**Comment by tonybaloney** [comment]
@jwattier I was going with individual but aggregate is important. If your project has hundreds of files the graph will be unreadable

**Comment by jwattier** [comment]
@tonybaloney Agreed. Perhaps then some functionality to allow for either option (e.g., a default scenario of individual then a flag for kicking to aggregate only or aggregate+individuals). 

This also makes me think there could be room for another metric....number of files. Mwahahaha :-)
