### ISSUE TITLE
Show version number in CLI

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/wily#38]
`--help` command should show `wily.__version__` in heading.

Also a `--version`/`-V` flag should be available in the CLI

**Comment by DahlitzFlorian** [comment]
I'm working on this issue as my first contribution to wily and as my first contribution to any open source project.

**Comment by tonybaloney** [comment]
It’s all yours! If you have any questions or want any help on git flow let me know.

**Comment by DahlitzFlorian** [comment]
Thanks! I already added the `--version`/`-V` flag, but I'm still struggling with the `--help` heading as it's auto-generated and it seems that no way to inject it properly exists. Let's see if I can fix it in the next days.
