### ISSUE TITLE
Cannot override targets from wily.cfg

### ISSUE THREAD

**Issue by richardhanson** [tonybaloney/wily#58]
Example wily.cfg file:
```
[wily]
max_revisions = 100
path = ./tests,config.py,./load
```
Run:
`wily build`

Expected behavior:
Generates wily cache. Existing code in the `WilyConfig` class has support for defaulting the targets to the passed path.

Actual behavior:
Prints help message because `targets` are missing.

Possible Solution:
Remove `required=True` from the click option, set `config.targets` only if targets are passed, and do a check that `config.targets` are defined before running `build`.

**Comment by tonybaloney** [comment]
thanks for reporting, fixed in #57
