### ISSUE TITLE
Jupyter noteboooks

### ISSUE THREAD

**Issue by caheredia** [tonybaloney/wily#71]
Not working with jupyter notebooks. Because of the underlying notebooks JSON code, does this make it too difficult to capture metrics?

**Comment by tonybaloney** [comment]
There are ways of linting in Jupyter, but the way Wily is written would require significant refactoring.
Alternatively, the feature could be added to the radon library.

**Comment by tonybaloney** [comment]
working on in #95

**Comment by tonybaloney** [comment]
Shipped in 1.13.0
