### ISSUE TITLE
Applicability of Apache Lincese Version 2.0

### ISSUE THREAD

**Issue by vezeli** [tonybaloney/wily#89]
In the Apache License Version 2.0 at [the official website](https://www.apache.org/licenses/LICENSE-2.0.html) (as well as in the LICENSE file in this project) there is a section on how to apply the Apache License to a project and it states that the short license should be included together with the source files in the form of comment. I found additional information about file headers [here](https://www.apache.org/legal/src-headers.html#headers) with some even shorter versions. So my question is: _Is the Apache License Version 2.0 legally valid for this project without specifying the file header in every file or not?_

As an example, @theacodes is using Apache License Version 2.0 in the [nox project](https://github.com/theacodes/nox) and is actually including file headers to every file.

I understand most projects contain files scattered around different directories and that it could be useful to have license information in each file in case that someone copies a single file this way the license information is retained. However, in the same time I feel that, for practical reasons, most of the time it is more useful for developers to have good documentation as file header.

**Comment by tonybaloney** [comment]
>> So my question is: Is the Apache License Version 2.0 legally valid for this project without specifying the file header in every file or not?

Yes.

Having a license header is a requirement for ASF projects, e.g. Apache Kafka, Apache Libcloud. The link in your comment is regarding ASF projects.

For projects using the license, it's not a requirement. The `LICENSE` file is.

I'm a member of the ASF for what it's worth

There are other conventions used by Python projects, like having a `__license__` in the module attribute, which would be a consideration.

**Comment by vezeli** [comment]
I would like to use the Apache License v2.0 though was not sure how it applies to projects (I got mislead  with the appendix mostly). Thanks so much for clearing this out!

Sorry if the previous post sounded somewhat arrogant (I realized only later that it could have been written better) but my intention was the best from the start :yum:

**Comment by tonybaloney** [comment]
>>> Sorry if the previous post sounded somewhat arrogant (I realized only later that it could have been written better) but my intention was the best from the start 😋

Not at all, I'm happy to have the question. I did have to read the license again to double-check (it's not obvious!)
