### ISSUE TITLE
Reducing the amount of work by using git diffs?

### ISSUE THREAD

**Issue by tino** [tonybaloney/wily#90]
I'd like to run this on a medium sized repository (50k+ sloc) for quite a bit of history, but it takes a really really long time (left it running over night with the intention to do 2000 commits, but that didn't get halfway). If I understand it correctly, it currently processes *all files* for *all commits*. Is that correct? Would it be possible to only do it again for files that changed between revisions, that would save a huge amount of work.

**Comment by tonybaloney** [comment]
That is an amazing idea!

**Comment by tonybaloney** [comment]
See #97

**Comment by tonybaloney** [comment]
Released in 1.14.0
